/**
 * THE IMAGE REGISTRY. Every image on the site is declared here, with its alt text.
 *
 * The `Image` component takes a KEY from this file — it has no `src` prop and no `alt` prop. That
 * is the whole point: alt text is a required field on the record, so an image with no alt text is
 * a TypeScript error rather than something an accessibility audit finds in six months.
 *
 * Writing alt text: describe the image for someone who cannot see it. It is not a place for
 * keywords. "Dog poop removal Ardmore PA weekly service" helps nobody and is exactly the kind of
 * thing that reads as manipulation. For the logo, the alt is simply the company name, because
 * that is what the image communicates.
 */

import type { Asset } from "./types";

export const assets = {
  /**
   * THE logo — the header lockup's picture half, cropped tight to the artwork's own edges so the
   * space around it in the header comes from layout rather than from transparent pixels baked
   * into the file. The wordmark beside it is live text, not part of this image.
   *
   * Note the dimensions: 483×405 is not square. Declaring it square is what makes the header jump
   * as the image loads, so the registry carries the real numbers and assets.test.ts checks them
   * against the file on every run.
   */
  logoMark: {
    src: "/brand/blues-poop-scoop--logo-cropped.png",
    alt: "Blue's Poop Scoop",
    width: 483,
    height: 405,
  },
  /** The full lockup, artwork and wordmark together. For social cards and print, not the header. */
  logoFull: {
    src: "/brand/blues-poop-scoop--logo--full.png",
    alt: "Blue's Poop Scoop — pet waste removal",
    width: 1024,
    height: 1024,
  },
} as const satisfies Record<string, Asset>;

export type AssetKey = keyof typeof assets;

/** The default social share card, generated by scripts/generate-icons.mjs. */
export const ogDefault = {
  src: "/brand/og-default.png",
  alt: "Blue's Poop Scoop — pet waste removal",
  width: 1200,
  height: 630,
} satisfies Asset;
