/**
 * THE IMAGE REGISTRY. Every image on the site is declared here, with its alt text.
 *
 * The `Image` component takes a KEY from this file — it has no `src` prop and no `alt` prop. That
 * is the whole point: alt text is a required field on the record, so an image with no alt text is
 * a TypeScript error rather than something an accessibility audit finds in six months.
 *
 * Writing alt text: describe the image for someone who cannot see it. It is not a place for
 * keywords. "Dog poop removal Ardmore PA weekly service" helps nobody and is exactly the kind of
 * thing that reads as manipulation. For the logo, the alt is simply the company name, because
 * that is what the image communicates.
 */

import type { Asset } from "./types";

export const assets = {
  /**
   * THE logo — the header lockup's picture half, cropped tight to the artwork's own edges so the
   * space around it in the header comes from layout rather than from transparent pixels baked
   * into the file. The wordmark beside it is live text, not part of this image.
   *
   * Note the dimensions: 483×405 is not square. Declaring it square is what makes the header jump
   * as the image loads, so the registry carries the real numbers and assets.test.ts checks them
   * against the file on every run.
   */
  logoMark: {
    src: "/brand/blues-poop-scoop--logo-cropped.png",
    alt: "Blue's Poop Scoop",
    width: 483,
    height: 405,
  },
  /**
   * The homepage hero photograph — the owners and the dog the business is named after. A real
   * photo of the actual people is the single hardest thing for a franchise competitor to match,
   * which is why it sits above the fold rather than a stock lawn.
   */
  landingHero: {
    src: "/landing--hero.jpg",
    alt: "The owners of Blue's Poop Scoop in branded sweatshirts, holding their small white dog outdoors",
    width: 3000,
    height: 2000,
  },
  /**
   * The "why us" band. Portrait, and cropped to a band on a phone — see the note in `WhyUs`.
   * Downsized from the 4000×6000 original: nothing on the page renders it wider than ~600 CSS
   * pixels, and shipping the camera's file is 2.7MB of nothing.
   */
  whyUs: {
    src: "/why-us.jpg",
    alt: "The owners of Blue's Poop Scoop kneeling on a lawn with their small white dog",
    width: 2000,
    height: 3000,
  },
  /**
   * ── THE SERVICE CARDS ──────────────────────────────────────────────────────
   * One per service, for the 2×2 grid on /services/. All four are cropped square-ish by
   * `object-cover` in a fixed-height box, so what matters in each is that the subject sits near
   * the middle — the top and bottom of a tall frame are the first things the crop takes.
   */

  /**
   * Poop Scoop. The only one of the four that is a photograph of the actual business — the owners,
   * in branded shirts, with the real scooper. Downsized from the camera's 4000×6000: nothing
   * renders it wider than ~600 CSS pixels and the original was 4MB.
   */
  servicePoopScoop: {
    src: "/services--poop-scoop.jpg",
    alt: "Two Blue's Poop Scoop staff beside a dog waste station, one holding a scooper",
    width: 1200,
    height: 1800,
  },
  /** Deodorizer. Stock — a pump sprayer treating a lawn. Replace when there is a photo of the real work. */
  serviceDeodorizer: {
    src: "/services--deodorizer.jpg",
    alt: "A gloved worker kneeling on a lawn, spraying it with a handheld pump sprayer",
    width: 1031,
    height: 797,
  },
  /** Haul Away. Stock — a loaded skip on a driveway. */
  serviceHaulAway: {
    src: "/services--haul-away.webp",
    alt: "A blue skip on a driveway, filled with household junk and bagged waste",
    width: 1920,
    height: 1280,
  },
  /** One-Time Clean. Stock — a caddy of cleaning supplies. */
  serviceOneTimeClean: {
    src: "/services--one-time-clean.jpg",
    alt: "A yellow bucket packed with brushes, cloths, gloves and spray bottles",
    width: 1200,
    height: 675,
  },

  /** The full lockup, artwork and wordmark together. For social cards and print, not the header. */
  logoFull: {
    src: "/brand/blues-poop-scoop--logo--full.png",
    alt: "Blue's Poop Scoop — pet waste removal",
    width: 1024,
    height: 1024,
  },
} as const satisfies Record<string, Asset>;

export type AssetKey = keyof typeof assets;

/** The default social share card, generated by scripts/generate-icons.mjs. */
export const ogDefault = {
  src: "/brand/og-default.png",
  alt: "Blue's Poop Scoop — pet waste removal",
  width: 1200,
  height: 630,
} satisfies Asset;
