/**
 * GENERATED by scripts/build-service-area.mjs — do not edit by hand.
 *
 * The outline of every serviced zip, dissolved into one shape and encoded as a Google polyline.
 * Re-run the script after changing the zip list in cities.ts; lib/maps.test.ts fails if you don't.
 *
 * Source: US Census ZCTA (ZIP Code Tabulation Area) boundaries, simplified to 0.0005°.
 */

/** The territory, as a Google-encoded polyline. Feeds `path=enc:` on the Maps Static API. */
export const serviceAreaOutline =
  "arhsFvzdkMp\\yEhA_G|EkAoCySdJwEpSu@rAcGbTaLbNkb@zQgTxLe[xFcd@nJ`LpYqi@lFmX}Hsh@tPnD|B{D|GyNhB_Y~KmCk@oIvQeXhDyUuf@ei@qFcPbLmTgDsKzGcQkJcZdLeKoQeJ}No[`Vig@ra@o`@qJwFiBlD}R{LhD{CoFsCGeN|KfNtSoSvKfNvKyP~Dx@hFqNtRdIlJkDtFqK~AfEyAmEhE_FjPmHAcFxJgGdCw[~FgCnLi[yEs]rCqIjK{DiJgV`AaXlFuM~Pd@jKdQ|MeKf\\|OpPg@xf@{\\|Bag@pHgDvJbGhCcFw@wY~GmBvHjItOhEqDj[rRdN|XGj[jTfa@iElH~DzD_ChVtZjCyHrHx@zLlSlFwLb]~YtDgBtPdM|E{BxLzLtCjPdSpBZhKbD~ClGiBz@eJ`IhIjH{N`C~NrEbBvG_IfHZlI{DzBe_AmB}VpXan@{\\ki@tI}xA{BaX`^~@vXs[{e@ogA{X{[e}AR{DrDed@eE}IrEdC}M|YkKcOc_B|Gan@lA}xAhFw_AtOiv@cn@m\\q~@sMgNYipA|e@oi@lIm_AVgm@mEoh@sTiq@ykA_^gfAyUghA_F{`AkQ}~@iNcZsa@gk@{`@mYed@sJyk@i\\q`@mf@_`@moAw^cbCu{Ce|EeSeW}]~b@sDlVwPvGcRe[{QvCwOwCub@mm@aKkIeNoAaGmm@y^{[y_@gFuOjAg\\gMyOpc@e`@sCmWdPiEvIoMmKs^m@yR~HfH`]oP|Uu@xX|BbKaDtQsJEeH|FhAhV_FrGoJ~BsAl[_XqH}HbGxZxYq~@ljBvb@ja@zcD`kFv|BrxBhIdTda@vb@j{@j|@t`@ey@ti@nh@dm@|lAbU~Pa`F`dK{f@ec@sAwChI_BmAyBgDoBsIpAqQcNlBwDs\\{_@iAw^tBkR_EsEeDcW}cAwcAfBpBk]`u@gNcNdFqIcAcD{H~I`B~AqFrAqZ_Omj@biAgCncAtQx~@`UzThQcVfZ|Y_B~CnJ~I`Pu]xWlV{CpKxAjN~JgPv^|c@`FYbEeHkJpkAyMlUmQtJz]|d@jJv\\vJyE}@mU|E|UqFdIQfIdRfw@pHtFvI@oDhN`j@`j@kA~^jPuOpwDvcEqdA|aAuWpO_W`]dB`^rTdsAFl^pAs\\iWowAYqYnOiWp_Ayq@dAnBobAbs@{Hp`@rY~aC~KNfIrW{G`Dz@rWbQbs@rKpOxUnt@kYnUz[z]hQlg@fTsOhcAng@vIfMeDj`@`AeC~@dJbJrJjDcAhBrPzTVoKbi@~GrGl@|TaI~O|GzZmFjDzT`r@nNfL";

/** South-west and north-east corners, for anything that needs to frame the shape itself. */
export const serviceAreaBounds = {
  south: 39.867,
  west: -75.39644,
  north: 40.13799,
  east: -74.95578,
};

/** The zips this shape was built from. Compared against `servicedZips` by the test. */
export const serviceAreaZips: string[] = [
  "19003",
  "19004",
  "19010",
  "19035",
  "19038",
  "19041",
  "19072",
  "19085",
  "19096",
  "19102",
  "19103",
  "19104",
  "19106",
  "19107",
  "19109",
  "19111",
  "19114",
  "19115",
  "19116",
  "19118",
  "19119",
  "19120",
  "19121",
  "19122",
  "19123",
  "19124",
  "19125",
  "19126",
  "19127",
  "19128",
  "19129",
  "19130",
  "19131",
  "19132",
  "19133",
  "19134",
  "19135",
  "19136",
  "19137",
  "19138",
  "19139",
  "19140",
  "19141",
  "19142",
  "19143",
  "19144",
  "19145",
  "19146",
  "19147",
  "19148",
  "19149",
  "19150",
  "19151",
  "19152",
  "19153",
  "19154",
];
