/**
 * The ad platforms' tracking, in one place: Google Ads conversions and the Meta pixel.
 *
 * TWO IDS, BOTH PUBLIC. They ship inside the browser bundle and name an ad account, nothing more —
 * neither is a secret, and neither can be used to spend anyone's money. They live in the
 * environment rather than in a constant here for one reason: a preview deployment that reports
 * conversions poisons the real account's data, and Smart Bidding then optimises toward whatever
 * a preview URL happened to do. Set these in Vercel's PRODUCTION environment only. Blank is the
 * safe state and switches the whole file off — the same call `lib/turnstile.ts` makes about its
 * own key, for the same reason: the site's job is taking leads, and it must not stop taking them
 * because a tag is unconfigured.
 */

/** From Google Ads → Admin → Data manager → Google tag. The `AW-` prefix is part of the value. */
export const googleAdsId = process.env.NEXT_PUBLIC_GOOGLE_ADS_ID ?? "";

/** From Meta Events Manager → Data sources → the pixel. A bare number, no prefix. */
export const metaPixelId = process.env.NEXT_PUBLIC_META_PIXEL_ID ?? "";

/**
 * The conversion action's event name, as generated by Google Ads. It is NOT a name we chose and
 * NOT a name we may tidy up: Google matches the conversion by this exact string, so a rename here
 * silently stops every sign-up from counting while the tag keeps reporting success. It changes
 * only if someone creates a new conversion action in the Ads UI, and then it changes to whatever
 * that screen says.
 *
 * There is deliberately no `send_to`. This account uses the newer event-name conversions, where
 * the `config` call above is what routes the event; a `send_to` conversion label would be the
 * older pairing and is not what the Ads UI handed us.
 */
const GOOGLE_ADS_SIGNUP_EVENT = "ads_conversion_Sign_up_1";

/** Which form produced the lead. Reported as a parameter so the two can be told apart in-platform. */
export type LeadSource = "quick_lead" | "contact";

declare global {
  interface Window {
    dataLayer?: unknown[];
    gtag?: (...args: unknown[]) => void;
    fbq?: (...args: unknown[]) => void;
    _fbq?: unknown;
  }
}

/**
 * WHY A HANDOFF FLAG AND NOT JUST "FIRE ON /thank-you/".
 *
 * Every form on this site lands on /thank-you/, which makes that page the obvious conversion
 * trigger — and it is, but only for people who got there by submitting something. The page is a
 * real URL: it survives a refresh, a back-then-forward, and a bookmark, and each of those would
 * report another sign-up that never happened. Google would then bid harder on whatever traffic
 * refreshes pages.
 *
 * So the form sets a flag as it navigates and /thank-you/ spends it. One submit, one conversion,
 * and a reload finds nothing left to claim. `sessionStorage` because the flag must not outlive the
 * tab, and because it survives the navigation itself — which a variable in memory would not, the
 * form component being unmounted by the very thing it is trying to report.
 */
const PENDING_KEY = "bps:lead-pending";

/** Wrapped because Safari's private mode throws on `sessionStorage` rather than returning null. */
function session(): Storage | null {
  try {
    return typeof window === "undefined" ? null : window.sessionStorage;
  } catch {
    return null;
  }
}

/** Called by a form immediately before it navigates to /thank-you/. */
export function markLeadPending(source: LeadSource): void {
  session()?.setItem(PENDING_KEY, source);
}

/** Reads and clears in one step, so a second caller finds nothing. Null means "not a real submit". */
function consumeLeadPending(): LeadSource | null {
  const store = session();
  const value = store?.getItem(PENDING_KEY) ?? null;
  if (value) store?.removeItem(PENDING_KEY);
  return value === "quick_lead" || value === "contact" ? value : null;
}

/**
 * Reports one sign-up to both platforms, or does nothing at all.
 *
 * Returns silently when there is no pending flag — that is the refresh case, and it is the normal
 * path for most views of /thank-you/ over a site's life. `window.gtag` and `window.fbq` are
 * optional-called rather than assumed: an ad blocker, an offline tag script, or an unset ID all
 * leave them undefined, and none of those are worth an exception on a page whose actual job is
 * telling someone their message was sent.
 */
export function reportSignup(): void {
  const source = consumeLeadPending();
  if (!source) return;

  // Google Ads: the conversion. `form` is a custom parameter — visible in the Ads UI only if
  // someone defines it there, but it costs nothing to send and answers "which form?" when asked.
  window.gtag?.("event", GOOGLE_ADS_SIGNUP_EVENT, { form: source });

  // Meta: the standard `Lead` event, which is the one their optimisation understands. `PageView`
  // alone builds an audience; this is what lets Meta learn who fills forms in.
  window.fbq?.("track", "Lead", { content_name: source });
}
