/**
 * THE METADATA BUILDER. Every page calls this and no page hand-rolls a <meta> tag.
 *
 * What it guarantees, for free, on every page:
 *   · a self-referencing canonical on the real origin
 *   · a unique title and description (the compiler requires both)
 *   · Open Graph + Twitter card tags that agree with the canonical
 *   · noindex on anything that is not the production deployment
 *
 * Those four are the overwhelming majority of "technical SEO" on a marketing site, and each one
 * is the kind of thing that silently regresses when it is copy-pasted per page.
 */

import type { Metadata } from "next";

import { ogDefault } from "@/content/assets";
import { site } from "@/content/site";
import type { Seo } from "@/content/types";
import { SITE_URL, absoluteUrl, isIndexable } from "./routes";

type BuildMetadataArgs = Seo & {
  /** Site-relative path of THIS page, e.g. "/services/weekly-scooping/". */
  path: string;
  /** Overrides the default social share image. */
  ogImage?: { url: string; width: number; height: number; alt: string };
  /**
   * Set on pages that must never be indexed (thank-you pages, in-progress flows). Content pages
   * never set this — indexability is decided by the deployment, not per page.
   */
  noindex?: boolean;
};

export const metadataBase = new URL(SITE_URL);

/**
 * The default share image, generated by scripts/generate-icons.mjs. Absolute URL, because every
 * social platform fetches it from a server that has no idea what our origin is.
 */
const defaultOgImage = {
  url: absoluteUrl(ogDefault.src),
  width: ogDefault.width,
  height: ogDefault.height,
  alt: ogDefault.alt,
};

export function buildMetadata({
  title,
  description,
  path,
  ogImage,
  noindex = false,
}: BuildMetadataArgs): Metadata {
  const canonical = absoluteUrl(path);
  const image = ogImage ?? defaultOgImage;
  const indexable = isIndexable && !noindex;

  return {
    title,
    description,
    metadataBase,
    alternates: {
      // Self-referencing canonical. Consolidates any parameter or slash variant onto one URL.
      canonical,
    },
    robots: {
      index: indexable,
      follow: indexable,
      googleBot: {
        index: indexable,
        follow: indexable,
        // Allow full rich previews; the default caps snippet length for no benefit.
        "max-snippet": -1,
        "max-image-preview": "large",
        "max-video-preview": -1,
      },
    },
    openGraph: {
      type: "website",
      siteName: site.name,
      title,
      description,
      url: canonical,
      locale: "en_US",
      images: [image],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [image.url],
    },
  };
}
